11_TableView/PhuocN/TableView1/TableView/TableView.xcodeproj/project.pbxproj, 11_TableView/PhuocN/TableView1/TableView/TableView.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 11_TableView/PhuocN/TableView1/TableView/TableView.xcodeproj/xcuserdata/phuocnguyen.xcuserdatad/xcschemes/xcschememanagement.plist, 11_TableView/PhuocN/TableView1/TableView/TableView/AppDelegate.swift, 11_TableView/PhuocN/TableView1/TableView/TableView/Base.lproj/LaunchScreen.storyboard, 11_TableView/PhuocN/TableView1/TableView/TableView/Base.lproj/Main.storyboard, 11_TableView/PhuocN/TableView1/TableView/TableView/Controller/Home/HomeViewController.swift, 11_TableView/PhuocN/TableView1/TableView/TableView/Controller/Home/HomeViewController.xib, 11_TableView/PhuocN/TableView1/TableView/TableView/Controller/Profile/ProfileViewController.swift, 11_TableView/PhuocN/TableView1/TableView/TableView/Info.plist, 11_TableView/PhuocN/TableView1/TableView/TableView/Models/DataManagement/DataManagement.swift, 11_TableView/PhuocN/TableView1/TableView/TableView/Models/Objects/User.swift, 11_TableView/PhuocN/TableView1/TableView/TableView/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json, 11_TableView/PhuocN/TableView1/TableView/TableView/Resource/Assets.xcassets/Contents.json, 11_TableView/PhuocN/TableView1/TableView/TableView/Resource/users.plist, 11_TableView/PhuocN/TableView1/TableView/TableView/SceneDelegate.swift, 11_TableView/PhuocN/TableView1/TableView/TableView/ViewController.swift
=> Phuoc Nguyen - Exercise 11 - TableView - Tạo project mẫu 

08_MVC/PhuocN/MVC/MVC.xcodeproj/project.pbxproj, 08_MVC/PhuocN/MVC/MVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 08_MVC/PhuocN/MVC/MVC.xcodeproj/xcuserdata/phuocnguyen.xcuserdatad/xcdebugger/Breakpoints_v2.xcbkptlist, 08_MVC/PhuocN/MVC/MVC.xcodeproj/xcuserdata/phuocnguyen.xcuserdatad/xcschemes/xcschememanagement.plist, 08_MVC/PhuocN/MVC/MVC/AppDelegate.swift, 08_MVC/PhuocN/MVC/MVC/Assets.xcassets/AppIcon.appiconset/Contents.json, 08_MVC/PhuocN/MVC/MVC/Assets.xcassets/Contents.json, 08_MVC/PhuocN/MVC/MVC/Base.lproj/LaunchScreen.storyboard, 08_MVC/PhuocN/MVC/MVC/Base.lproj/Main.storyboard, 08_MVC/PhuocN/MVC/MVC/Controller/CaculationViewController.swift, 08_MVC/PhuocN/MVC/MVC/Controller/CaculationViewController.xib, 08_MVC/PhuocN/MVC/MVC/Controller/CaculatorViewController.swift, 08_MVC/PhuocN/MVC/MVC/Controller/CaculatorViewController.xib, 08_MVC/PhuocN/MVC/MVC/Enumerations/Enum.swift, 08_MVC/PhuocN/MVC/MVC/Info.plist, 08_MVC/PhuocN/MVC/MVC/Model/Number.swift, 08_MVC/PhuocN/MVC/MVC/Model/Operator.swift, 08_MVC/PhuocN/MVC/MVC/SceneDelegate.swift, 08_MVC/PhuocN/MVC/MVC/View/CaculationButton.swift, 08_MVC/PhuocN/MVC/MVC/View/CaculatorButton.swift, 08_MVC/PhuocN/MVC/MVC/ViewController.swift, _templates/PracticeTemplate/PracticeTemplate.xcodeproj/xcuserdata/phuocnguyen.xcuserdatad/xcschemes/xcschememanagement.plist
Tạo máy tính thực hiện các phép tính cộng trừ nhân chia theo mô hình MVC
=> Phuoc Nguyen - Exercise 08 - MVC

08_MVC/TienTranV/CalculatorMVC/CalculatorMVC.xcodeproj/project.pbxproj, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/AppDelegate.swift, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Assets.xcassets/AppIcon.appiconset/Contents.json, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Assets.xcassets/Contents.json, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Base.lproj/LaunchScreen.storyboard, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Controller/CalculatorViewController.swift, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Controller/CalculatorViewController.xib, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Info.plist, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Models/Number.swift, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/Models/Operator.swift, 08_MVC/TienTranV/CalculatorMVC/CalculatorMVC/SceneDelegate.swift
Bài tập Calculator sử dụng mô hình MVC.
=> Tien Tran V. - Exercise 08 - MVC

01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard.xcodeproj/project.pbxproj, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/AppDelegate.swift, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Assets.xcassets/AppIcon.appiconset/Contents.json, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Assets.xcassets/Contents.json, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Base.lproj/LaunchScreen.storyboard, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/ContentView.swift, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Home/HomeViewController.swift, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Home/HomeViewController.xib, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Info.plist, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Preview Content/Preview Assets.xcassets/Contents.json, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/SceneDelegate.swift
=> NguyenVuD - Baitap01 

01_GioiThieu/AnNguyen/BaiTap01/BaiTap01.xcodeproj/project.pbxproj, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/AppDelegate.swift, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/Assets.xcassets/AppIcon.appiconset/Contents.json, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/Assets.xcassets/Contents.json, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/Base.lproj/LaunchScreen.storyboard, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/HomeViewController.swift, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/HomeViewController.xib, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/Info.plist, 01_GioiThieu/AnNguyen/BaiTap01/BaiTap01/SceneDelegate.swift
Random đổi màu background view
=> AnNguyenT.2 - BaiTap01

01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard.xcodeproj/project.pbxproj, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/AppDelegate.swift, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Assets.xcassets/AppIcon.appiconset/Contents.json, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Assets.xcassets/Contents.json, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Base.lproj/LaunchScreen.storyboard, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/ContentView.swift, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Home/HomeViewController.swift, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Home/HomeViewController.xib, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Info.plist, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/Preview Content/Preview Assets.xcassets/Contents.json, 01_GioiThieu/NguyenVu/NoStoryBoard/NoStoryBoard/SceneDelegate.swift, 02_SwiftBasic/NguyenVuD/basic.playground/Contents.swift, 02_SwiftBasic/NguyenVuD/basic.playground/contents.xcplayground
- Tổng của 100 số Fibonacy đầu tiên  
- Liệt kê 100 số Fibonacy đầu tiên  
- Tính sin(x), cos(x) bằng công thức Chuỗi Taylor  
- Liệt kê các số hạnh phúc bé hơn 10.000
elemToReplace with substitutionElem.
=> Nguyen Vu D. - Exercise 02 - Basic Swift

02_SwiftBasic/AnNT/BaiTap01.playground/Contents.swift, 02_SwiftBasic/AnNT/BaiTap01.playground/contents.xcplayground, 02_SwiftBasic/AnNT/BaiTap02.playground/Contents.swift, 02_SwiftBasic/AnNT/BaiTap02.playground/contents.xcplayground, 02_SwiftBasic/AnNT/BaiTap03.playground/Contents.swift, 02_SwiftBasic/AnNT/BaiTap03.playground/contents.xcplayground, 02_SwiftBasic/AnNT/BaiTap04.playground/Contents.swift, 02_SwiftBasic/AnNT/BaiTap04.playground/contents.xcplayground, 02_SwiftBasic/AnNT/BaiTap05.playground/Contents.swift, 02_SwiftBasic/AnNT/BaiTap05.playground/contents.xcplayground, 02_SwiftBasic/AnNT/BaiTap06.playground/Contents.swift, 02_SwiftBasic/AnNT/BaiTap06.playground/contents.xcplayground, 02_SwiftBasic/AnNT/BaiTap07.playground/Contents.swift, 02_SwiftBasic/AnNT/BaiTap07.playground/contents.xcplayground
- Tính diện tích và thể tích hình cầu.
- Tính phương trình bậc 2 : ax^2 + bx + c = 0
- Giải hệ phương trình bậc nhất 2 ẩn số
- Tổng của 100 số Fibonacy đầu tiên
- Liệt kê 100 số Fibonacy đầu tiên
- Tính sin(x), cos(x) bằng công thức Chuỗi Taylor
- Liệt kê các số hạnh phúc bé hơn 10.000
- Tìm chuỗi con trong chuỗi mẹ
- Hoán vị random các phần tử trong mãng
=> An Nguyen T. - Exercise 2 - SwiftBasic

03_SwiftOOP/HienM/baitap01.playground/Contents.swift, 03_SwiftOOP/HienM/baitap01.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap02,03.playground/Contents.swift, 03_SwiftOOP/HienM/baitap02,03.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap04.playground/Contents.swift, 03_SwiftOOP/HienM/baitap04.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap05.playground/Contents.swift, 03_SwiftOOP/HienM/baitap05.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap06.playground/Contents.swift, 03_SwiftOOP/HienM/baitap06.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap07.playground/Contents.swift, 03_SwiftOOP/HienM/baitap07.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap08.playground/Contents.swift, 03_SwiftOOP/HienM/baitap08.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap09.playground/Contents.swift, 03_SwiftOOP/HienM/baitap09.playground/contents.xcplayground, 03_SwiftOOP/HienM/baitap10.playground/Contents.swift, 03_SwiftOOP/HienM/baitap10.playground/contents.xcplayground, 03_SwiftOOP/TienTranV/BaiTap03.playground/Contents.swift
Hoàn thành bài tập phần OOP 
nguyên.
- Khởi tạo Stack.
- Kiểm tra Stack rỗng.
- Kiểm tra Stack đầy.
- Thêm một phần tử vào stack.
-  Xoá một phần tử ở đỉnh stack.
và cho phép in ra được thông tin của các hình như diện tích, chu vi, thể
tích...
sinh và tổng điểm. Sắp xếp theo thứ tự giảm dần của tổng điểm. Khi
tổng điểm như nhau thì học sinh có năm sinh nhỏ hơn được đứng
trước. In ra danh sách học sinh đã sắp xếp sao cho tất cả các chữ cái
đầu của họ tên chuyển thành chữ hoa.
Các hàm thành phần bao gồm: hàm tạo, hàm truy cập dữ liệu, hàm
normalize() để chuẩn hóa dữ liệu nằm trong khoảng quy định của
ngày tháng năm
hàm thành phần gồm:
Hàm khởi tạo mảng
Hàm in mảng
Hàm in phần tử lớn nhất, phần tử nhỏ nhất của mảng
S=1+2+3+...+n (n nguyên dương)
=> Hien Mai .V .N/Exercise - OOP

BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop.xcodeproj/project.pbxproj, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/AppDelegate/SceneDelegate.swift, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/Controllers/Base/BaseTabBarController.swift, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/Controllers/Base/BaseViewController.swift, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/Controllers/Detail/DetailViewController.swift, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/Controllers/Favorites/FavoriteViewController.swift, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/Controllers/Home/HomeViewController.swift, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/Controllers/Map/MapViewController.swift, BaiTapTongHop/HanhNH/BaiTapTongHop/BaiTapTongHop/Controllers/Profile/ProfileViewController.swift
=> Hanh.N.H - BaiTapTongHop - TabBar

03_SwiftOOP/VienH/Baitap3.5_3.6._3.9playground.playground/Contents.swift, 03_SwiftOOP/VienH/Baitap3.5_3.6._3.9playground.playground/contents.xcplayground, 03_SwiftOOP/VienH/baitap3.1.playground/Contents.swift, 03_SwiftOOP/VienH/baitap3.1.playground/contents.xcplayground, 03_SwiftOOP/VienH/baitap3.10.playground/Contents.swift, 03_SwiftOOP/VienH/baitap3.10.playground/contents.xcplayground, 03_SwiftOOP/VienH/baitap3.2_3.3_3.4.playground/Contents.swift, 03_SwiftOOP/VienH/baitap3.2_3.3_3.4.playground/contents.xcplayground, 03_SwiftOOP/VienH/baitap3.7_3.8.playground/Contents.swift, 03_SwiftOOP/VienH/baitap3.7_3.8.playground/contents.xcplayground
Bai tap 1: Viết phương trình nhập 2 phân số và in ra kết quả
Bai tap 2: Tính chu vi đa giác
Bai tap 3: Tính chu vi và diện tích tam giác
Bai tap 4: Nhập vào 1 dãy n tam giác và in ra màn hình các cạnh của tam giác
Bai tap 5: Mô tả hoạt động của ngăn xếp
Bai tap 6: tính thể tích, chu vi, diện tích theo các lớp
Bai tap 7: In ra danh sách học sinh
Bai tap 8: Xây dựng lớp Date và chuẩn hóa dữ liệu nằm trong khoản quy định của ngày, tháng , năm.
Bai tap 9: Khởi tạo mảng và in mảng trong lớp số nguyên
Bai tap 10: Viết chương trình tính toán một lớp A.
=> VienH. - Exercise 3 - OOP

02_SwiftBasic/HienM/BaiTap03.playground/Contents.swift, 02_SwiftBasic/HienM/BaiTap03.playground/contents.xcplayground, 02_SwiftBasic/HienM/BaiTap04.playground/Contents.swift, 02_SwiftBasic/HienM/BaiTap04.playground/contents.xcplayground, 02_SwiftBasic/HienM/BaiTap05.playground/Contents.swift, 02_SwiftBasic/HienM/BaiTap05.playground/contents.xcplayground, 02_SwiftBasic/HienM/BaiTap06.playground/Contents.swift, 02_SwiftBasic/HienM/BaiTap06.playground/contents.xcplayground, 02_SwiftBasic/HienM/BaiTap07.playground/Contents.swift, 02_SwiftBasic/HienM/BaiTap07.playground/contents.xcplayground, 02_SwiftBasic/HienM/baiTap01.playground/Contents.swift, 02_SwiftBasic/HienM/baiTap01.playground/contents.xcplayground, 02_SwiftBasic/HienM/baiTap02.playground/Contents.swift, 02_SwiftBasic/HienM/baiTap02.playground/contents.xcplayground
-  Tổng của 100 số Fibonacy đầu tiên
-  Liệt kê 100 số Fibonacy đầu tiên
-  Tính sin(x), cos(x) bằng công thức Chuỗi Taylor
-  Liệt kê các số hạnh phúc bé hơn 10.000
elemToReplace with substitutionElem.
=> Hien Mai V. - Exercise 02 - Basic Swift

BaiTestOOP-CustomView/AnNT/OOP.playground/Contents.swift, BaiTestOOP-CustomView/AnNT/OOP.playground/contents.xcplayground
=> Finished OOP

01_GioiThieu/LamLT/BaiTap1/BaiTap1.xcodeproj/project.pbxproj, 01_GioiThieu/LamLT/BaiTap1/BaiTap1.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 01_GioiThieu/LamLT/BaiTap1/BaiTap1.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/AppDelegate.swift, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/Assets.xcassets/AppIcon.appiconset/Contents.json, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/Assets.xcassets/Contents.json, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/Base.lproj/LaunchScreen.storyboard, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/Info.plist, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/MyViewController.swift, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/MyViewController.xib, 01_GioiThieu/LamLT/BaiTap1/BaiTap1/SceneDelegate.swift
Bài tập 1
Tạo project với 1 màn hình và 1 button 
Click vào button đổi màu background của màn hình theo random.
=> Lam Le T. - Exercise 01- Gioi Thieu

06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing.xcodeproj/project.pbxproj, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/AppDelegate.swift, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/Assets.xcassets/AppIcon.appiconset/Contents.json, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/Assets.xcassets/Contents.json, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/Info.plist, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/SceneDelegate.swift, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/baitap01-Chartting/ChartViewController.swift, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/baitap01-Chartting/ChartViewController.xib, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/baitap01-Chartting/FxRectangularView.swift, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/baitap02-Chartting/ChartCircleViewController.swift, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/baitap02-Chartting/ChartCircleViewController.xib, 06_Drawing/HienM/BaiTap06-Drawing/BaiTap06-Drawing/baitap02-Chartting/DrawCircleView.swift
=> HienM. - Execise 06 - Drawing

02_SwiftBasic/LamLT/Bai1.playground/Contents.swift, 02_SwiftBasic/LamLT/Bai1.playground/contents.xcplayground, 02_SwiftBasic/LamLT/Bai2.playground/Contents.swift, 02_SwiftBasic/LamLT/Bai2.playground/contents.xcplayground, 02_SwiftBasic/LamLT/Bai3.playground/Contents.swift, 02_SwiftBasic/LamLT/Bai3.playground/contents.xcplayground, 02_SwiftBasic/LamLT/Bai4.playground/Contents.swift, 02_SwiftBasic/LamLT/Bai4.playground/contents.xcplayground, 02_SwiftBasic/LamLT/Bai5.playground/Contents.swift, 02_SwiftBasic/LamLT/Bai5.playground/contents.xcplayground, 02_SwiftBasic/LamLT/Bai6.playground/Contents.swift, 02_SwiftBasic/LamLT/Bai6.playground/contents.xcplayground, 02_SwiftBasic/LamLT/Bai7.playground/Contents.swift, 02_SwiftBasic/LamLT/Bai7.playground/contents.xcplayground
=> Lam L T. -Exercise 2- Swift Basic

02_SwiftBasic/AnhPD/BaiTap1.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap1.playground/contents.xcplayground, 02_SwiftBasic/AnhPD/BaiTap2.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap2.playground/contents.xcplayground, 02_SwiftBasic/AnhPD/BaiTap3.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap3.playground/contents.xcplayground, 02_SwiftBasic/AnhPD/BaiTap4.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap4.playground/contents.xcplayground, 02_SwiftBasic/AnhPD/BaiTap5.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap5.playground/contents.xcplayground, 02_SwiftBasic/AnhPD/BaiTap6.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap6.playground/contents.xcplayground, 02_SwiftBasic/AnhPD/BaiTap7.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap7.playground/contents.xcplayground
- Liệt kê 100 số Fibonacy đầu tiên
- Tính sinx cosx bằng chuỗi Taylor
=> Anh pd/bai tap02

01_GioiThieu/QuanBT/Baitap01/Baitap01.xcodeproj/project.pbxproj, 01_GioiThieu/QuanBT/Baitap01/Baitap01.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 01_GioiThieu/QuanBT/Baitap01/Baitap01.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 01_GioiThieu/QuanBT/Baitap01/Baitap01/AppDelegate.swift, 01_GioiThieu/QuanBT/Baitap01/Baitap01/Assets.xcassets/AppIcon.appiconset/Contents.json, 01_GioiThieu/QuanBT/Baitap01/Baitap01/Assets.xcassets/Contents.json, 01_GioiThieu/QuanBT/Baitap01/Baitap01/Info.plist, 01_GioiThieu/QuanBT/Baitap01/Baitap01/SceneDelegate.swift, 01_GioiThieu/QuanBT/Baitap01/Baitap01/ViewController.swift, 01_GioiThieu/QuanBT/Baitap01/Baitap01/ViewController.xib
=> QuânBT Bài 01

02_SwiftBasic/AnhPD/BaiTap1.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap2.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap3.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap4.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap5.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap6.playground/Contents.swift, 02_SwiftBasic/AnhPD/BaiTap7.playground/Contents.swift
Tính tổng và liệt kê 100 số fibonacy
Tính sinx và cosx theo chuỗi Taylor
Liệt kê các số hạnh phúc bé hơn 10000
=> AnhPD-BaiTap2-SwiftBasic

03_SwiftOOP/AnhPD/BaiTap1.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap1.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap10.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap10.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap2.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap2.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap3.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap3.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap4.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap4.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap5.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap5.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap6.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap6.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap7.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap7.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap8.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap8.playground/contents.xcplayground, 03_SwiftOOP/AnhPD/BaiTap9.playground/Contents.swift, 03_SwiftOOP/AnhPD/BaiTap9.playground/contents.xcplayground
S = 1 + 2 + 3+ ... + n (số nguyên dương)
=> AnhPD-BaiTapOOP

02_SwiftBasic/QuanBT/BaiTap01.playground/Contents.swift, 02_SwiftBasic/QuanBT/BaiTap01.playground/contents.xcplayground, 02_SwiftBasic/QuanBT/BaiTap02.playground/Contents.swift, 02_SwiftBasic/QuanBT/BaiTap02.playground/contents.xcplayground, 02_SwiftBasic/QuanBT/BaiTap03.playground/Contents.swift, 02_SwiftBasic/QuanBT/BaiTap03.playground/contents.xcplayground, 02_SwiftBasic/QuanBT/BaiTap04.playground/Contents.swift, 02_SwiftBasic/QuanBT/BaiTap04.playground/contents.xcplayground, 02_SwiftBasic/QuanBT/BaiTap05.playground/Contents.swift, 02_SwiftBasic/QuanBT/BaiTap05.playground/contents.xcplayground, 02_SwiftBasic/QuanBT/BaiTap06.playground/Contents.swift, 02_SwiftBasic/QuanBT/BaiTap06.playground/contents.xcplayground, 02_SwiftBasic/QuanBT/BaiTap07.playground/Contents.swift, 02_SwiftBasic/QuanBT/BaiTap07.playground/contents.xcplayground
[] Tính diện tích và thể tích hình cầu
[] Giải phương trình bậc 2
[] Giải hệ phương trình
[] Tính các chuỗi số : 
- Tổng 100 số fibonacy
- Liệt kê 100 số fibonacy
- Tính sinx, cosx bằng chuỗi taylor
- Liệt kê số hạnh phúc
[] Tìm chuỗi con trong chuỗi mẹ
[] Hoán vị các phần tử trong mãng
[] Thay thế phần tử trong mãng theo điều kiện
=> Quan Bui T. - Bai Basic Swift - Exercise 2

03_SwiftOOP/QuanBT/BaiTap01.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap01.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap02+03.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap02+03.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap04.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap04.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap05.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap05.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap06.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap06.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap07.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap07.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap08.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap08.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap09.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap09.playground/contents.xcplayground, 03_SwiftOOP/QuanBT/BaiTap10.playground/Contents.swift, 03_SwiftOOP/QuanBT/BaiTap10.playground/contents.xcplayground
[]Thiết lập lớp phân số: hàm cộng, trừ, nhân, chia
[]Xây dựng lớp Đa Giác: hàm tính chu vi, in các cạnh
[]Lớp Tam Giác kế thừa Đa Giác: thêm hàm tính diện tích
[]Xây dựng ứng dụng kiểm tra tam giác thoả mãn định lý Pitago
[]Xây dựng lớp CStack: mô tả hoạt động của ngăn xếp
[]Xây dựng các lớp theo sơ đồ
[]Xây dựng danh sách học sinh và được sắp xếp theo điều kiện
[]Xây dựng lớp Date: định dạng ngày tháng năm
[]Xây dựng lớp mảng 1 chiều: tìm min max
[]xây dựng lớp A tính tổng n số nguyên
=> Quan Bui T. - Bai OOP - Execise 3

06_Drawing/LamLT/Bai1/Bai1.xcodeproj/project.pbxproj, 06_Drawing/LamLT/Bai1/Bai1.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 06_Drawing/LamLT/Bai1/Bai1.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 06_Drawing/LamLT/Bai1/Bai1/AppDelegate.swift, 06_Drawing/LamLT/Bai1/Bai1/Assets.xcassets/AppIcon.appiconset/Contents.json, 06_Drawing/LamLT/Bai1/Bai1/Assets.xcassets/Contents.json, 06_Drawing/LamLT/Bai1/Bai1/Base.lproj/Main.storyboard, 06_Drawing/LamLT/Bai1/Bai1/ChartView.swift, 06_Drawing/LamLT/Bai1/Bai1/ChartViewController.swift, 06_Drawing/LamLT/Bai1/Bai1/ChartViewController.xib, 06_Drawing/LamLT/Bai1/Bai1/Info.plist, 06_Drawing/LamLT/Bai1/Bai1/SceneDelegate.swift, 06_Drawing/LamLT/Bai2/Bai2.xcodeproj/project.pbxproj, 06_Drawing/LamLT/Bai2/Bai2.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 06_Drawing/LamLT/Bai2/Bai2.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 06_Drawing/LamLT/Bai2/Bai2/AppDelegate.swift, 06_Drawing/LamLT/Bai2/Bai2/Assets.xcassets/AppIcon.appiconset/Contents.json, 06_Drawing/LamLT/Bai2/Bai2/Assets.xcassets/Contents.json, 06_Drawing/LamLT/Bai2/Bai2/Info.plist, 06_Drawing/LamLT/Bai2/Bai2/PieChartView.swift, 06_Drawing/LamLT/Bai2/Bai2/SceneDelegate.swift, 06_Drawing/LamLT/Bai2/Bai2/ViewController.swift, 06_Drawing/LamLT/Bai2/Bai2/ViewController.xib
=> Lâm LT_Bài 6 Drawing

06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing.xcodeproj/project.pbxproj, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/AppDelegate.swift, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/Assets.xcassets/AppIcon.appiconset/Contents.json, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/Assets.xcassets/Contents.json, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/BaiTap01/ChartViewController.swift, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/BaiTap01/ChartViewController.xib, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/BaiTap01/MyChart.swift, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/BaiTap02/MyPieChart.swift, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/BaiTap02/PieChartViewController.swift, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/BaiTap02/PieChartViewController.xib, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/Base.lproj/LaunchScreen.storyboard, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/Info.plist, 06_Drawing/QuanBT/BaiTapDrawing/BaiTapDrawing/SceneDelegate.swift
=> Quan Bui T - Bai tap Drawing

03_SwiftOOP/LamLT/Bai1.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai1.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai10.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai10.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai2AndBai3.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai2AndBai3.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai4.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai4.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai5.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai5.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai6.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai6.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai7.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai7.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai8.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai8.playground/contents.xcplayground, 03_SwiftOOP/LamLT/Bai9.playground/Contents.swift, 03_SwiftOOP/LamLT/Bai9.playground/contents.xcplayground
=> Lâm Lê T.-Exercise 3_OOP

01_GioiThieu/ThinhN/Baitap1/Baitap1.xcodeproj/project.pbxproj, 01_GioiThieu/ThinhN/Baitap1/Baitap1.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 01_GioiThieu/ThinhN/Baitap1/Baitap1.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 01_GioiThieu/ThinhN/Baitap1/Baitap1/AppDelegate.swift, 01_GioiThieu/ThinhN/Baitap1/Baitap1/Assets.xcassets/AppIcon.appiconset/Contents.json, 01_GioiThieu/ThinhN/Baitap1/Baitap1/Assets.xcassets/Contents.json, 01_GioiThieu/ThinhN/Baitap1/Baitap1/Base.lproj/LaunchScreen.storyboard, 01_GioiThieu/ThinhN/Baitap1/Baitap1/Home/MyViewController.swift, 01_GioiThieu/ThinhN/Baitap1/Baitap1/Home/MyViewController.xib, 01_GioiThieu/ThinhN/Baitap1/Baitap1/Info.plist, 01_GioiThieu/ThinhN/Baitap1/Baitap1/Preview Content/Preview Assets.xcassets/Contents.json, 01_GioiThieu/ThinhN/Baitap1/Baitap1/SceneDelegate.swift, Baitap1/Baitap1.xcodeproj/project.pbxproj, Baitap1/Baitap1.xcodeproj/project.xcworkspace/contents.xcworkspacedata, Baitap1/Baitap1.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, Baitap1/Baitap1/AppDelegate.swift, Baitap1/Baitap1/Assets.xcassets/AppIcon.appiconset/Contents.json, Baitap1/Baitap1/Assets.xcassets/Contents.json, Baitap1/Baitap1/Base.lproj/LaunchScreen.storyboard, Baitap1/Baitap1/ContentView.swift, Baitap1/Baitap1/Info.plist, Baitap1/Baitap1/Preview Content/Preview Assets.xcassets/Contents.json, Baitap1/Baitap1/SceneDelegate.swift
=> Thinh N.(6) .-Exercise 01-Gioi Thieu 

BaiKiemTra/AnhPD/BaiTest/BaiTest.xcodeproj/project.pbxproj, BaiKiemTra/AnhPD/BaiTest/BaiTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata, BaiKiemTra/AnhPD/BaiTest/BaiTest.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, BaiKiemTra/AnhPD/BaiTest/BaiTest/AppDelegate.swift, BaiKiemTra/AnhPD/BaiTest/BaiTest/Assets.xcassets/AppIcon.appiconset/Contents.json, BaiKiemTra/AnhPD/BaiTest/BaiTest/Assets.xcassets/Contents.json, BaiKiemTra/AnhPD/BaiTest/BaiTest/Info.plist, BaiKiemTra/AnhPD/BaiTest/BaiTest/SceneDelegate.swift, BaiKiemTra/AnhPD/BaiTest/BaiTest/ViewController.swift, BaiKiemTra/AnhPD/BaiTest/BaiTest/ViewController.xib, BaiKiemTra/AnhPD/BaiTestOOP.playground/Contents.swift, BaiKiemTra/AnhPD/BaiTestOOP.playground/contents.xcplayground
=> AnhPD-BaiTest

08_MVC/AnhPD/BaiTapMVC/BaiTapMVC.xcodeproj/project.pbxproj, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/AppDelegate.swift, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/Assets.xcassets/AppIcon.appiconset/Contents.json, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/Assets.xcassets/Contents.json, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/Calculator.swift, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/Info.plist, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/SaveData.swift, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/SceneDelegate.swift, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/ViewController.swift, 08_MVC/AnhPD/BaiTapMVC/BaiTapMVC/ViewController.xib
=> AnhPD-BaiTapMVC

03_SwiftOOP/ThinhN/Baitap1.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap1.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap10.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap10.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap2.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap2.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap3.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap3.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap4.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap4.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap5.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap5.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap6.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap6.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap7.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap7.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap8.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap8.playground/contents.xcplayground, 03_SwiftOOP/ThinhN/Baitap9.playground/Contents.swift, 03_SwiftOOP/ThinhN/Baitap9.playground/contents.xcplayground
=> Thinh N(6) - BaiTap3 -Swift OOP

08_MVC/LamLT/CalculatorMVC/CalculatorMVC.xcodeproj/project.pbxproj, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/AppDelegate/AppDelegate.swift, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/AppDelegate/SceneDelegate.swift, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/Controller/CalculatorViewController.swift, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/Controller/CalculatorViewController.xib, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/Info.plist, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/Models/Calculator.swift, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json, 08_MVC/LamLT/CalculatorMVC/CalculatorMVC/Resource/Assets.xcassets/Contents.json
=> LamLT LamLT Exersice 8 MVC

08_MVC/QuanBT/BaiTapMVC/BaiTapMVC.xcodeproj/project.pbxproj, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/contents.xcworkspacedata, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/AppDelegate/AppDelegate.swift, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/AppDelegate/SceneDelegate.swift, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Assets.xcassets/AppIcon.appiconset/Contents.json, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Assets.xcassets/Contents.json, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Base.lproj/LaunchScreen.storyboard, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Controllers/MVCViewController.swift, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Controllers/MVCViewController.xib, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Info.plist, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Models/Operands.swift, 08_MVC/QuanBT/BaiTapMVC/BaiTapMVC/Models/ProcessingCalculations.swift
=> Quan Bui T - Bai tap MVC

02_SwiftBasic/ThinhN(2)/MyPlayground.playground/Contents.swift, 02_SwiftBasic/ThinhN(2)/MyPlayground.playground/contents.xcplayground
=> ThịnhN - Basic swift 
